config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resource :purchases, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :merchant
  monetize :price_cents,
           presence: true,
           numericality: { greater_than_or_equal_to: 0 }

  validates_presence_of :description

  accepts_nested_attributes_for :merchant

  private

  def autosave_associated_records_for_merchant
    self.merchant = Merchant.where(name: merchant.name)
                            .create_with(address: merchant.address)
                            .first_or_create do |m|
                              m.name = merchant.name
                              m.address = merchant.address
                            end
  end
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates_presence_of :name, :address
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :item
  validates_presence_of :count, :name
  validates_numericality_of :count,
                            greater_than_or_equal_to: 0,
                            only_integer: true

  accepts_nested_attributes_for :item

  private

  def autosave_associated_records_for_item
    self.item = Item.joins(:merchant)
                    .where(
                      items: { description: item.description },
                      merchants: { name: item.merchant.name }
                    )
                    .first_or_create do |i|
                      i.description = item.description
                      i.merchant = item.merchant
                      i.price = item.price
                    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def create
    params = file_params || {}
    @response = UploadAndSumPurchases.call(file: params[:purchases]&.tempfile)
  end

  private

  def file_params
    params.require(:file).permit(:purchases) if params[:file].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTabFilesProcess</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<section id="home" class="d-flex align-items-center">
  <div class="container">
    <div class="card col-sm-6 offset-sm-3">
      <%= simple_form_for  :file, url: purchases_path,remote: true ,html: { class:"card-body"  } do |f| %>
        <%= f.input :purchases, as: :file, label:false, required: true, input_html:{ accept: ".tab"}   %>
        <%= f.button :submit, 'Upload File', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>
</section>

app/views/purchases/create.js.erb
<% if @response.success?%>
Swal.fire({
    text: 'Total gross income is <%=@response.sum.format%>',
    title: 'Your work has been saved',
    icon: 'success',
    confirmButtonText: 'Ok'
});
<% else %>
Swal.fire({
    html: "<%=@response.error %>",
    title: 'Error',
    icon: 'error',
    confirmButtonText: 'Ok',
});
<%end%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon flex-end">
  <div class="container">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>